bot:
  token: 5789698291:AAGMq0pQR_ahxe2q3vHbxg6SGU51w_7J7QY
  username: t.me/spendmoneyTemp_bot


spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/expenses
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false


server:
  port: 5000