package org.expense_bot.enums;

public enum ConversationState {
  CONVERSATION_STARTED,
  WAITING_FOR_CATEGORY,
  WAITING_FOR_SUM,
  WAITING_CHECK_CATEGORY,
  WAITING_FOR_PERIOD,
  WAITING_CATEGORY_ACTION,
  PROCESS_ACTION,
  WAITING_FINAL_ACTION,
  WAITING_SETTINGS_ACTION,
  WAITING_FINAL_SETTING_ACTION,
  WAITING_STICKERS_ACTION,
  WAITING_INIT_ACTION, WAITING_INCOME_ACTION, WAITING_INCOME_СHECK_PERIOD, WAITING_ENTERED_ACTION, WAITING_EXPENSE_ACTION, WAITING_STICKERS_FINAL_ACTION, WAITING_FOR_SUM_ANOTHER_DATE;

  ConversationState() {
  }
}
