insert into stickers (token, action, enabled) values
  ('CAACAgIAAxkBAAEGcvtjdVRqztgveFZcS462zBoc-uW6dQACHgAD6dgTKLO-IwM5OGbpKwQ','SUCCESS_EXPENSE_SUM',true),
  ('CAACAgIAAxkBAAEGcvtjdVRqztgveFZcS462zBoc-uW6dQACHgAD6dgTKLO-IwM5OGbpKwQ','SUCCESS_INCOME_SUM',true),
  ('CAACAgIAAxkBAAEGcxFjdVTOfe8zl3AYpB6qP3Cm7MyZewACDgAD6dgTKBOmPUNf-EgfKwQ','ADDED_YOUR_CATEGORY',true),
  ('CAACAgIAAxkBAAEGcxVjdVTyMon_GB8QtIt3P1hxME1u0wACEAAD6dgTKG-_RsOvAAHBFisE','ALREADY_EXISTS_CATEGORY',true),
  ('CAACAgEAAxkBAAEGcxtjdVU_k5gSgRhOfQkNdPp0yvWDpgAC8AADOA6CEa7hNLhQEjvIKwQ','BIG_EXPENSE_SUM',true),
  ('CAACAgIAAxkBAAEGcxVjdVTyMon_GB8QtIt3P1hxME1u0wACEAAD6dgTKG-_RsOvAAHBFisE','WRONG_ENTERED_SUM',true),
  ('CAACAgEAAxkBAAEGcxdjdVUUGd0yVljPeHe0ASk9JQN_wAAC5QADOA6CEce0HKzXIwH1KwQ','NOTHING_FOR_TODAY',true),
  ('CAACAgEAAxkBAAEGcyFjdVWKU-DKc2wXKYp7IOgmCJG3NQAC4AADOA6CEfL8_yejXdRWKwQ','DATE_FROM_FUTURE',true),
  ('CAACAgEAAxkBAAEGcydjdVX_6_6b1x9DCg-XNLFjBIkvxQAC5AADOA6CEUWZqh2dSykeKwQ','NOTIFICATION',true),
  ('CAACAgEAAxkBAAEGcyNjdVWdg92C4kp-BAdsPlLonn8PCgAC6QADOA6CEbG9i22p0OzyKwQ','HELLO',true);